name: Run Unit Tests

on:
  push:
    branches:
     - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 #Baixa o codigo do repo no "runner"
    - uses: actions/setup-node@v4 #Baixa o node no "runner"
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci #Instala todas dep
    - run: npm test #Roda os testes